### ISSUE TITLE
When will there be an upgrade to neo4j 4.1.3?

### ISSUE THREAD

**Issue by salehio** [neo4j-contrib/neo4j-helm#110]
Currently the helm char references 4.1.1 which contains some severe issues especially when running in docker. (example: https://github.com/neo4j/neo4j/issues/12564 ) 

When can we expect an update on the helm chart?

Thanks!

**Comment by moxious** [comment]
@salehio when we've got a few extra PRs in, we'll release an updated version.

But in the meantime - you can set the image tag you want to use easily using values.yaml.

If you send a parameter imageTag, it'll use whatever you specifify.  The default is:

```
imageTag: "4.1.2-enterprise"
```

If you want 4.1.3-enterprise *now*, just set that explicitly.
