### ISSUE TITLE
Link to values.yaml gives a 404

### ISSUE THREAD

**Issue by davidlrosenblum** [neo4j-contrib/neo4j-helm#12]
In https://neo4j-contrib.github.io/neo4j-helm/user-guide/USER-GUIDE.html the link to values.yaml gives a 404.
The hyper-link resolves to:
https://github.com/neo4j-contrib/neo4j-helm/blob/master/user-guide/values.yaml

**Comment by moxious** [comment]
thanks for the report.  Updated it.
