### ISSUE TITLE
V4.1.3-1 Not released correctly?

### ISSUE THREAD

**Issue by mvanderheijden** [neo4j-contrib/neo4j-helm#124]
Hi,

When I try to install the new version of the helm chart I get the following error:
`Can't get a valid version for repositories neo4j. Try changing the version constraint in requirements.yaml`
It worked correctly with version 4.1.1-3:
`Downloading neo4j from repo https://raw.githubusercontent.com/neo4j-contrib/neo4j-helm/master`
Also after the command `helm repo update && helm search neo4j` I only see neo4j/neo4j 4.1.1-3.

The CI tool of this repo shows an error `Trigger Publish / trigger_publish (push)` is this the cause?
Could you maybe realese the chart again?

Kind Regards,
Mike

**Comment by mvanderheijden** [comment]
I see that the `index.yaml` is not updated

**Comment by moxious** [comment]
I'll push an update to index.yaml for that new release.  But frankly not many folks were using this install method as it wasn't ideal for some helm clients.  Still, it was a miss on my part, I'll update soon.

**Comment by moxious** [comment]
This commit should fix the issue

https://github.com/neo4j-contrib/neo4j-helm/commit/e5dbf451f9b9e935f5aaf448a32895c70a3e19b2
