### ISSUE TITLE
Causal Cluster with SSL not connecting via bolt

### ISSUE THREAD

**Issue by salehio** [neo4j-contrib/neo4j-helm#128]
I have a causal cluster deployment of the helm chart on Azure via AKS.

The setup works great with HTTP.

After enabling HTTPS and exposing the associated ports and installing the certificates, I'm able to access the browser via SSL on port 7473, and there's no warning from the browser about an invalid cert.

When I go to connect, I get the following:
![image](https://user-images.githubusercontent.com/12577679/97507307-22593000-193a-11eb-81ad-43301a36978f.png)

`ServiceUnavailable: WebSocket connection failure. Due to security constraints in your web browser, the reason for the failure is not available to this Neo4j Driver. Please use your browsers development console to determine the root cause of the failure. Common reasons include the database being unavailable, using the wrong connection URL or temporary network problems. If you have enabled encryption, ensure your browser is configured to trust the certificate Neo4j is configured to use. WebSocket readyState is: 3`

Console states that the cert name is invalid.

I'm not sure how web sockets SSL works, but my guess is the problem that my pods advertise themselves on their IP.

I tried having them advertise themselves on the host name, but I couldn't manage to do it.

I opened a github issue on AKS to see how this is done (with additional explanation) here:
https://github.com/Azure/AKS/issues/1928

Could you explain how anyone has achieved SSL over bolt on kubernetes with a causal cluster and a single domain name?

Appreciate the help!

**Comment by moxious** [comment]
You are using the connection scheme `neo4j+s://` which requires you to have valid signed certs in place on the Neo4j server, which are trusted by your system CA.   Did you configure SSL certs in your neo4j Kubernetes instance?  If not -- that's the problem.

If you're using self-signed certs (which are the "out of the box default") then you need to set your connection string to `neo4j+ssc://` to explicitly tell the driver it's OK to use an insecure certificate.

See table 2 at this link: https://neo4j.com/docs/driver-manual/current/client-applications/

**Comment by salehio** [comment]
Hey @moxious 

I do have the certs set up, and they are trusted by my CA. So visiting mycooldomain.com resolves to my 0th node's IP address, where I have ports 80 and 7474  mapped to port 7474 internally (via load balancer) and ports 443 and 7473 mapped to 7473 internally (also via load balancer). If I visit on 443, I correctly end up on the browser page with no warning.

What is confusing to me is that the websockets connection is failing with an invalid cert error. My guess is because they advertise themselves by IP address since they don't have a host name.

If all of my nodes advertise themselves by their IP address, it makes sense that the SSL verification would fail. So even though I do have a host that matches my cert domain, and that host maps to my 0th node in my causal cluster, it's not sufficient to do that. Instead we need all nodes to expose themselves under that host name for that cert to work for all 3 nodes in my causal cluster.

This is where I'm attempting to expose all 3 nodes under the same domain, but I'm finding it difficult to do so. Does that make more sense?

**Comment by moxious** [comment]
You should not expose all 3 nodes under the same domain, period.  Unfortunately this is a fairly complex area of Neo4j as a product.  I've tried to write up a lot of details here on how this bit of the product works:  https://medium.com/neo4j/querying-neo4j-clusters-7d6fde75b5b4

I really recommend reading on that and making sure your deployment architecture makes sense before proceeding.  The advertised address is in fact key; if you advertise a bare IP address rather than a hostname, then you're bound to have problems for sure.  Similarly, if you advertise all 3 machines under the same address, you will definitely have problems and that article I linked is the explanation why.

It's for those reasons that we recommend 3 separate IPs / hostnames, as you can see in the external exposure instructions.

**Comment by moxious** [comment]
Connection errors owing to confusions with advertised addresses, SSL, and network routing are very common issues that arise.  Without seeing your config and knowing your network, it's not possible to give a clean clear suggestion on how to get through it, but the resources I've linked on this ticket address all of the issues, and should give you the map you need to resolve them.

**Comment by salehio** [comment]
Thanks for your responses, @moxious!

Just to summarize:
If I want to expose 3 graph nodes in a causal cluster externally with SSL, I must:
1- Have 3 separate IPs
2- Have 3 separate hostnames
3- Have 3 separate SSL certificates

Is that correct?

**Comment by moxious** [comment]
Yes, you've got that all right. 

The hostnames are needed for the SSL, because SSL typically only applies to hostnames, not bare IPs.  

Separate addresses are needed because of "smart client" routing (covered in the article).

In this repo, the approach we take is to expose 1 lb or clusteirp *per core member* to separately expose those IPs to the outside world (the external exposure docs).  The reason this is done is because if you put *1* address and *1* LB in front of a cluster, you will be defeating and undoing the way the smart client routing works.

**Comment by salehio** [comment]
Maybe I'm missing something here, but I still don't understand why the smart routing can't be achieved by having the members advertise themselves on different ports over the same host name.

That way you can still target individual members via port, and use a single domain and certificate.

The only issue I see with this is support for it on AKS, hence the linked issue I opened on the AKS side.

**Comment by moxious** [comment]
you could do that.  That's called "port spreading" (advertising the same host, different ports).  This is bad for different reasons though.  You'll tend to have a default for clients to connect to (myhost:7687).  If that member is down, your cluster is up but your clients can't reach it.

When you end up with 3 different addresses all on the same port, people will then create a single DNS entry with 3 pointers to the 3 different addresses.  Then configure all of your clients to talk to that single DNS entry.  Via DNS round robin, you'll always get connected with a smart client even if one member is down.  Can't say the same about port spreading

**Comment by salehio** [comment]
That makes sense. The only reason I dismissed DNS round robin is probably because of an assumption I failed to verify.

With DNS round robin, how can individual members still be targeted while SSL is on? I'd assume that DNS would be used to resolve the IPs of the members, but then you do not have an SSL hostname verification working because you are working with individual IPs.

Does using DNS roundrobin prevent you from using SSL certificates?

**Comment by moxious** [comment]
DNS roundrobin and SSL certs are different ideas, and they can work together.  It happens like this:

1. Client gets given a single address myserver:7687
2. Behind that record are 3 other addresses:   myserver1, myserver2, myserver3
3. Client gets resolved to one of them, client connects to that.  It has a valid cert for myserver1, no problems
4. Client gets a routing table for the cluster, which includes all 3 DNS entries, all with valid certs

The "fronting DNS record" gets used just as a pointer to the real 3 DNS entries the cluster is actually using

**Comment by salehio** [comment]
I see. So the DNS round robining solves the issue of having an address that targets a single IP, but you still need 3 separate host names and 3 separate SSL certificates. Is that correct?

**Comment by moxious** [comment]
yes

**Comment by moxious** [comment]
I believe this has been answered by the discussion.  If I've closed this in error, please open a new issue with details on your configuration, what you expect, and what's not happening correctly.
