### ISSUE TITLE
Enable configuration of individual advertise addresses

### ISSUE THREAD

**Issue by phoerious** [neo4j-contrib/neo4j-helm#130]
I need to expose my Neo4j cluster via Nodeports for clients outside the Kubernetes cluster, which proves almost impossible.

I need a way to give each core pod an individual address with different ports, otherwise write requests will go to an arbitrary pod and not necessarily the leader. The only way I see right now for achieving this is patching the init script, which is not really a solution.

**Comment by phoerious** [comment]
My current workaround:

```bash
# Patch init-script
kubectl patch configmap/graph-init-script --patch "$(kubectl get configmap/graph-init-script -o json | jq '.data["init.sh"] = "core_idx=$(hostname | sed ''s|.*-||'')\nexport NEO4J_dbms_connector_bolt_advertised__address=\"myhost0$((10 * $core_idx + 10)).example.com:$((30780 + $core_idx))\"\n" + .data["init.sh"]')"

# Restart deployment
kubectl rollout restart statefulset.apps/graph-neo4j-core
```

This patches the init-script config map to insert two lines at the beginning, setting the advertise address to `myhost0XX.example.com:30780X` based on the pod ID (adapt calculation to your needs).

The patch has to be applied again if you upgrade your Helm deployment.

**Comment by moxious** [comment]
There is an entire chapter in the docs that discusses this need & techniques extensively.   Have you read it?  Please do have a look.  Of the material that is here, why is this approach not suitable?  Because it's the best available current recommendation.

https://neo4j.com/labs/neo4j-helm/1.0.0/externalexposure/

**Comment by phoerious** [comment]
I read a lot of documentation, but it all assumed that I have multiple IPs and one single DNS name with multiple IPs for all pods, which does not work with NodePorts. I did indeed miss the per-host configuration you linked, which seems to work (although the whole environment variable juggling is extremely complicated compared to how easy, e.g., Elastic's ECK configuration is).

**Comment by moxious** [comment]
I agree this is a very complicated piece of how Neo4j in Kubernetes works.  Always open to suggestions on how to make it more simple & easy, but the complexity comes from Neo4j's need to know its network address when you configure it, in order to enable the "smart client routing architecture".  Other products such as Elastic don't have the same constraints, and have more flexibility on how they can do network exposure.

**Comment by phoerious** [comment]
It would be easier, if Neo4j, like Elasticsearch, would simply take write requests on any node and forward them to the leader if necessary. It is kinda silly that the client needs to know the cluster topology (it can be beneficial, but it shouldn't be mandatory).

As for the Helm chart, a great improvement would be if you would simply allow for extending the K8S YAML instead of trying to rebuild everything with environment variables. Recreating a whole context-free configuration language with simple env var names is bound to cause chaos, confusion, and (as was in my case) trial and error until you got all the typos out of your spec and read the init script three times to understand what it does. It doesn't have to be as fully-featured as ECK, where you have a whole new API type, but you could at least allow extensions to the Pod spec. Or you could simply make the config map more readable by using the normal dot syntax instead of underscores, double underscores and weird `NEO4J_` and `what_happens_if_my_hostname_includes_dashes_NEO4J_` prefixes. I know this is something NEO4J does out of the box, but I believe it's more meant for a few selected overrides and not for fully configuring the prodoct.

A config map like this would be much easier to understand and document:

```yaml
data:
  global:
    dbms.default_advertised_address: "xyz"
    dbms.connector.http.advertised_address: "xyz"
  core_0:
    dbms.connector.bolt.advertised_address: "abc1"
  core_1:
    dbms.connector.bolt.advertised_address: "abc2"
    some.other.config: "foo"
```

You could then mount the needed subpaths and the parsing into env vars could be done by the startup script. Or you simply append them to the normal config file.
