### ISSUE TITLE
Reasoning for hard-coding LoadBalancer service for discovery?

### ISSUE THREAD

**Issue by duboisph** [neo4j-contrib/neo4j-helm#14]
Hi @moxious,

While deploying this new chart I've noticed a LoadBalancer service is used for the Core server discovery. Is there a specific reason to use this instead of eg. a ClusterIP?

Being forced to use a LoadBalancer per Core pod is quite a costly choice, at least on AWS. Also, depending on VPC setup etc, this exposes the pods to the outside world. LoadBalancers usually get deployed in public subnets, unless specified otherwise through the proper annotations.

I'm currently running a test with ClusterIP and that seems to work ok. I'd be happy to submit a PR to open the choice of service type.

**Comment by moxious** [comment]
Putting in place the LBs had to do with adapting a bit of colleague's code.  I understand your reasoning for the ClusterIPs though.  Please do submit that PR, I'll have a look and the reasoning is sound, assuming it passes CI tests and it's reasonably kubernetes distribution agnostic, I'll accept the PR (which it sounds like it would be)

**Comment by moxious** [comment]
A part of the reasoning for this can be when people set up clusters that are cross-datacenter or cross-kubernetes cluster.  In this case, you need to expose the discovery ports, externally in the sense that the remote cluster needs to be able to see them, but not external in the sense of being accessible to other clients.  Ports 5000, 6000, and 7000 should generally not be accessible to anyone other than other authorized cluster members.

I thing I'll need to add to the documentation is that LoadBalancers are necessary in those scenarios, but for the one kubernetes / one cluster scenario, they aren't.

**Comment by srfaytkn** [comment]
> A part of the reasoning for this can be when people set up clusters that are cross-datacenter or cross-kubernetes cluster. In this case, you need to expose the discovery ports, externally in the sense that the remote cluster needs to be able to see them, but not external in the sense of being accessible to other clients. Ports 5000, 6000, and 7000 should generally not be accessible to anyone other than other authorized cluster members.
> 
> I thing I'll need to add to the documentation is that LoadBalancers are necessary in those scenarios, but for the one kubernetes / one cluster scenario, they aren't.

hey moxious Can loadbalance type be optional?

**Comment by duboisph** [comment]
Hi @srfaytkn, I was going to create a PR  to do exactly that, however haven't had the time yet unfortunately.

I should get something ready in the next couple of days.
