### ISSUE TITLE
Is it possible to deploy neo4j community version with HA mode to Kubernetes?

### ISSUE THREAD

**Issue by keepWalking** [neo4j-contrib/neo4j-helm#141]
hi, experts, 
I know this repo is targeted at deploying Neo4j Enterprise Causal Clusters to Kubernetes instances. But just wondering whether it is doable to deploy neo4j community verstion with HA mode to Kubernetes instances.

**Comment by moxious** [comment]
No.  What introduces the possibility of high availability in Neo4j is the causal clustering architecture.

https://neo4j.com/docs/operations-manual/current/clustering/introduction/#causal-clustering-introduction

In turn, causal clustering is only available in Neo4j Enterprise.  As a result, you cannot run Neo4j community in HA mode - this is independent of kubernetes or VMs.
