### ISSUE TITLE
Unable to start helm Neo4j 4.2.0 

### ISSUE THREAD

**Issue by ShepardZhao** [neo4j-contrib/neo4j-helm#142]
Hi we cannot deploy the helm into the K8s with below message (neo4j 4.2.0)

**│ 2020-11-24 11:48:02.000+0000 ERROR Failed to start Neo4j on dbms.connector.http.listen_address, a socket address. If missing port or hostname it is acquired from dbms.default_listen_address.                                                                                         │
│ java.lang.RuntimeException: Error starting Neo4j database server at /data/databases**

here is our config in neo4j.conf

dbms.default_listen_address=0.0.0.0
dbms.memory.pagecache.size=512M
metrics.prometheus.endpoint=localhost:2004
metrics.prometheus.enabled=false
metrics.jmx.enabled=true
metrics.graphite.server=localhost:2003
metrics.graphite.interval=3s
metrics.graphite.enabled=false
metrics.csv.interval=3s
metrics.csv.enabled=true
dbms.tx_log.rotation.retention_policy=100M size
dbms.mode=CORE
dbms.jvm.additional=-XX:+ExitOnOutOfMemoryError -Duser.country=EN -Duser.language=EN -Duser.variant=Traditional_WIN
dbms.directories.plugins=/plugins
dbms.directories.logs=/data/logs
dbms.default.listen_address=0.0.0.0
dbms.default_database=neo4j
dbms.default_advertised_address=neo4j-neo4j-core-0.neo4j-neo4j.nous-prod-ns.svc.57.tess.io
dbms.connector.https.listen_address=0.0.0.0:7473
dbms.connector.https.advertised_address=neo4j-neo4j-core-0.neo4j-neo4j.nous-prod-ns.svc.57.tess.io:7473
dbms.connector.http.listen_address=0.0.0.0:7474
dbms.connector.http.advertised_address=neo4j-neo4j-core-0.neo4j-neo4j.nous-prod-ns.svc.57.tess.io:7474
dbms.connector.bolt.listen_address=0.0.0.0:7687
dbms.connector.bolt.advertised_address=neo4j-neo4j-core-0.neo4j-neo4j.nous-prod-ns.svc.57.tess.io:7687
dbms.backup.listen_address=0.0.0.0:6362
dbms.backup.enabled=true
causal_clustering.transaction_advertised_address=discovery-neo4j-neo4j-0.nous-prod-ns.svc.57.tess.io:6000
causal_clustering.raft_advertised_address=discovery-neo4j-neo4j-0.nous-prod-ns.svc.57.tess.io:7000
causal_clustering.minimum_core_cluster_size_at_runtime=2
causal_clustering.minimum_core_cluster_size_at_formation=3
causal_clustering.kubernetes.service_port_name=tcp-discovery
causal_clustering.kubernetes.label_selector=neo4j.com/cluster=neo4j-neo4j,neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)
causal_clustering.discovery_type=K8S
causal_clustering.discovery_advertised_address=discovery-neo4j-neo4j-0.nous-prod-ns.svc.57.tess.io:5000
dbms.security.auth_enabled=false

before error status 
│ 2020-11-25 11:04:36.851+0000 INFO  Database 'system' is waiting for a total of 3 core members...                                                                                                                                                                                       │

**Comment by moxious** [comment]
More information is needed on this to tell what's happening, as it's an issue related to core neo4j cluster formation.  What do your debug.log files say?
