### ISSUE TITLE
[Question] Can I use community image?

### ISSUE THREAD

**Issue by lukaszo** [neo4j-contrib/neo4j-helm#153]
Hello,

I apologize for asking here. If there is a better place to ask questions please tell me and I will close this issue.

I would like to know if I can use this charts with Neo4j community images?  I've used a following command: 
```bash
helm install neo4j neo4j-helm/neo4j  --version 4.2.0-1 --set core.standalone=true --set imageTag=4.2.0
```
and it worked fine. DB is installed and I can connect to it.

There is a version for community release https://github.com/equinor/helm-charts/tree/master/charts/neo4j-community but it's outdated and seems to be not maintained anymore.

Thank you in advance for the answers.

**Comment by moxious** [comment]
in theory -- yes you can.  We've heard reports others are doing the same and it seems to work.  Practically speaking, the helm chart will set a bunch of config parameters that don't apply to Neo4j Community at all, and Neo4j Community might (at most) ignore those and give you warnings or errors in your logs that such config is only available in Neo4j Enterprise.

I have to warn you though that this repo isn't intended for community, and it isn't tested in our CI build chain.  So there's no going forward guarantee that this will continue to work with future versions.

**Comment by moxious** [comment]
https://github.com/neo4j-contrib/neo4j-helm/issues/141

**Comment by lukaszo** [comment]
@moxious thank you for the answer. I don't think that this issue is a duplicate. I know that community image can run only in standalone mode. 
In the end I'm using this chart and is working ok. You answered my question, so issue can be closed anyway :)
