### ISSUE TITLE
Bug in defining neo4jPassword

### ISSUE THREAD

**Issue by fabio-510** [neo4j-contrib/neo4j-helm#158]
**Describe the bug**
Setting neo4jPassword has no effect due to error in the secret template

**To Reproduce**
1. Install with neo4jPassword variable set and without defining custom secret file

**Expected behavior**
secret file takes value from neo4jPassword parameter

**Additional context**
It only worked for me (using Helm 3) when I changed the following line from the secret.yaml template:

`{{ $password := .Values.neo4jPassword }}`
to
`{{ $password = .Values.neo4jPassword }}`

The variable $password is defined before as random string using ":=" operator. An attempt to redefine it using the ":=" operator is ignored, you need to use only "=" operator to reassign values in helm templates.

**Comment by moxious** [comment]
Fixed by PR contributed by a user -- already merged to master.    Next release should pick up this fix.   https://github.com/neo4j-contrib/neo4j-helm/pull/157

**Comment by fabio-510** [comment]
Nice, closing the issue.
