### ISSUE TITLE
function "lookup" not defined

### ISSUE THREAD

**Issue by andresfuentes** [neo4j-contrib/neo4j-helm#166]
**Describe the bug**
When using the chart I am receiving this error

Wait helm template failed. Error: parse error in "neo4j/templates/secret.yaml": template: neo4j/templates/secret.yaml:10: function "lookup" not defined : exit status 1

**To Reproduce**
just install Helm Chart

**Expected behavior**
The chart should install without any problems

**Error Logs**
Wait helm template failed. Error: parse error in "neo4j/templates/secret.yaml": template: neo4j/templates/secret.yaml:10: function "lookup" not defined : exit status 1

**Additional context**
Last time I used the chart it worked perfectly. This was about 4 weeks.

**Comment by eastlondoner** [comment]
hi @andresfuentes could you provide information about what version of helm you are using? (you can run `helm version`).

**Comment by andresfuentes** [comment]
I am using version 3

**Comment by andresfuentes** [comment]
I just found that the server has both version of helm, 2 and 3 and was using 2 before. once i use 3 it worked. thx

**Comment by eastlondoner** [comment]
No worries, thanks for the update
