### ISSUE TITLE
Helm Chart URL incorrect, causing "failed to download "neo4j/neo4j" at version "4.3.2-1"

### ISSUE THREAD

**Issue by meseta** [neo4j-contrib/neo4j-helm#209]
**Describe the bug**
It looks like 4.2.8-1 and 4.3.2-1 chart tgz files are at a different URL than what is listed in index.yaml

URL in helm chart:
`https://github.com/neo4j-contrib/neo4j-helm/releases/download/4.3.2-1/neo4j-4.3.2-1.tgz`

URL of actual file:
`https://github.com/neo4j-contrib/neo4j-helm/releases/download/v4.3.2-1/neo4j-4.3.2-1.tgz`
`--------------------------------------------------------------👆`

This causes it to become impossible to install 4.2.8-1 or 4.3.2-1 via helm with the following error:
```
Error: failed to download "neo4j/neo4j" at version "4.3.2-1" (hint: running `helm repo update` may help)
```

**To Reproduce**
1. `helm repo add neo4j https://neo4j-contrib.github.io/neo4j-helm`
2. `helm repo update` (for good measure)
3. `helm install neo4j neo4j/neo4j --version 4.3.2-1` (or equivalent, targeting version 4.3.2-1 or 4.2.8-1)

**Expected behavior**
Helm is able to download and install chart

**Comment by bfeshti** [comment]
Hi @meseta, I have updated the Tag in both releases and now it is able do download them.
Thanks for reporting this.
