### ISSUE TITLE
No jar URL found for version '4.1.0' - GDS on 4.1

### ISSUE THREAD

**Issue by bbenzikry** [neo4j-contrib/neo4j-helm#37]
Hi - first, thanks for the work on this chart :) 
I wasn't sure whether to open this in the GDS repository or not, but since the chart's default tag is 4.1 it seems appropriate. 
GDS [versions.json](https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/versions.json) doesn't seem to have any reference for 4.1 and so our pod logs show 
```
Error: No jar URL found for version '4.1.0' in versions.json from 'https://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/graph-data-science/versions.json'
```

Our chart is a fork which adds plugins via ```NEO4JLABS_PLUGINS```
```diff
- {{- if .Values.useAPOC }}
NEO4JLABS_PLUGINS: "[\"apoc\",\"graph-data-science\", \"n10s\"]"
- {{- end }}
```

**Comment by moxious** [comment]
You should open this in the GDS repository for sure.   The way that NEO4JLABS_PLUGINS works is by resolving that versions.json file for supported plugins to the official neo4j docker container.   If the right version isn't present for the right version of Neo4j, there's nothing that you can do in the context of the helm chart, except possibly use an initContainer to download the right JAR, put it in the /plugins folder and so forth.  (This is the approach for installing custom plugins, for example)

Sorry this isn't working for you, but this is probably release catch-up lag for GDS.

**Comment by moxious** [comment]
@bbenzikry the team that does GDS has told me that a preview release is available (this isn't baked into versions.json yet) and that a GA release is coming soon. https://neo4j.com/graph-data-science-1-3-0-preview-release-notes/

**Comment by bbenzikry** [comment]
@moxious Great, thanks for letting me know
