### ISSUE TITLE
Error: No jar URL found for version '4.1.1' in versions.json

### ISSUE THREAD

**Issue by EnziinSystem** [neo4j-contrib/neo4j-helm#74]
After install Helm chart, I get the message:
`
helm install neo4jgraph https://github.com/neo4j-contrib/neo4j-helm/releases/download/4.1.1-2/neo4j-4.1.1-2.tgz --set core.standalone=true --set acceptLicenseAgreement=yes --set neo4jPassword=developer
`

```
│ Configuration override prefix = neo4jgraph_neo4j_core_0                                                                                                                   │
│ Starting Neo4j CORE 0 on neo4jgraph-neo4j-core-0.neo4jgraph-neo4j.default.svc.cluster.local                                                                               │
│ Warning: Some files inside "/data" are not writable from inside container. Changing folder owner to neo4j.                                                                │
│ Changed password for user 'neo4j'.                                                                                                                                        │
│ Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json                                                         │
│ Error: No jar URL found for version '4.1.1' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'                                   │
│ stream closed  
```

**Comment by moxious** [comment]
Does your kubernetes cluster not have the ability to contact the internet?  The URL where versions.json is located is clear, and 4.1.1 of Neo4j is supported with APOC, so I'm imagining that what's going wrong here is the kubernetes pod's inability to fetch that URL

**Comment by EnziinSystem** [comment]
I use MicroK8S on the localhost, but the Kubernetes can connect to the internet.

**Comment by moxious** [comment]
When you launch the containers, try to shell into them and just install curl and try:

```
curl https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
```

You can check that URL right now - it's available, and there, and also mentions neo4j 4.1.1.  In fact the CI system for this repo uses APOC in exactly this way, so I'm sure this is working.   To help you with this issue, we need to know more about why your container in some context cannot fetch this file.  Or maybe it can fetch the file, but the content comes through differently for some reason.

**Comment by phoerious** [comment]
I have seen that quite a few times as well, but was was never able to reproduce it reliably. After enough restarts, it just goes away. But then it hangs in service discover (see #67).

**Comment by moxious** [comment]
Even if this isn't reliably reproducible in the context of installing the helm chart -- if you run into it, please do shell into the container and try to fetch the URL and see what else is going on.  I can't reproduce this at all, and short of a networking issue it's not clear what the cause could be.  We can continue to take this up but need some additional hint.

**Comment by moxious** [comment]
Here's the code path in the docker container where the failure message comes from: https://github.com/neo4j/docker-neo4j/blob/f431f75e1b2a1d6eec7a6902e1d52eda5891dd0f/docker-image-src/4.1/docker-entrypoint.sh#L163

The docker container fetches the file with `wget` (which could fail) and then uses `jq` to parse out the bit that it needs.  So if you can reproduce, you can also look inside of the container to see if you can locate a downloaded versions.json file.   The docker container appears not to clean up the file.

So if you shell in and *can't* find a versions.json file, this suggests wget is failing and it's a networking issue.  If you *can* find versions.json, this suggests it's a bash scripting error in the container itself.

**Comment by moxious** [comment]
Closed because of lack of response combined with presumptively being due to network conditions and/or failure to fetch the right JARs.

**Comment by Bajjuri15** [comment]
I am facing similar issue,  ERROR: No jar url found for version neo4j4.2.6 at https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json .
My kubernetes env doesnt have access to internet, so i cant do wget also. Is there any way to doit.

**Comment by eastlondoner** [comment]
@Bajjuri15 If your env has no connection to the internet then set `plugins: "[]"` in your values.yaml. Then the docker image will not try and install the apoc plugin. Neo4j works perfectly well without apoc :-)

If you *need* apoc in this situation then we recommend that you build a docker image inheriting from the neo4j docker image and add the apoc plugin (and any other plugins you need) to that docker image and put it in a container repository that your cluster can access. Let me know if you would like more guidance on how to do that.
