### ISSUE TITLE
Restore failed using neo4j restore.sh script

### ISSUE THREAD

**Issue by bugzyz** [neo4j-contrib/neo4j-helm#92]
Hi, based on my understanding of the code in restore.sh, I just want to confirm that:
1. Whether this is a logic mistake or I misunderstand the logic of the code
2. How to use this script correctly?

### My understanding(maybe misunderstanding😂):
Here, I think the restore.sh already limit the source database backup should be ended up with 'tar.gz' otherwise the restore_database function will return. (https://github.com/neo4j-contrib/neo4j-helm/blob/master/tools/restore/restore.sh#L70-L81)

But here, there are also some restore logic for those source database backup not ended up with 'tar.gz/gzip' (https://github.com/neo4j-contrib/neo4j-helm/blob/master/tools/restore/restore.sh#L93-L130). So it confused me wether this part of code took effect in this script.

Most important thing is that, I ran into some error when use this script. 😂
I exported several env as below:
_export BUCKET=gs://bucket_name_x/dir_name_y
export DATABASE=testdb
export GOOGLE_APPLICATION_CREDENTIALS=xxx
export FORCE_OVERWRITE=true_

And in the bucket: gs://bucket_name_x/dir_name_y, to meet the logic of your code, there is a tar file called testdb-latest.tar.gz which came from a database backup called testdb. I think the reason is here(the "data" in the middle of $RESTORE_FROM, https://github.com/neo4j-contrib/neo4j-helm/blob/master/tools/restore/restore.sh#L108). And below is the error message I got:

```
=== RESTORE testdb
You have an existing graph database at /data/databases/testdb
We will be force-overwriting any data present
Making restore directory
Copying gs://gcs_bucket_neo4j_poc_tpx/backup_in_highlimit_tared/testdb-latest.tar.gz -> /data/.restore
Copying gs://gcs_bucket_neo4j_poc_tpx/backup_in_highlimit_tared/testdb-latest.tar.gz...
- [1/1 files][ 29.1 MiB/ 29.1 MiB] 100% Done
Operation completed over 1 objects/29.1 MiB.
Backup size pre-uncompress:
30M	/data/.restore
total 29752
-rw-r--r-- 1 root root 30463507 Sep  3 10:20 testdb-latest.tar.gz
Untarring backup file
testdb/
... several line...
...
testdb/neostore.nodestore.db.labels
testdb/neostore.propertystore.db
BACKUP_SET_DIR was not specified, so I am assuming this backup set was formatted by my backup utility
BACKUP_FILENAME=testdb-latest.tar.gz
UNTARRED_BACKUP_DIR=testdb
UNZIPPED_BACKUP_DIR=
RESTORE_FROM=/data/.restore/data/testdb
Set to restore from /data/.restore/data/testdb - size on disk:
du: cannot access '/data/.restore/data/testdb': No such file or directory
Dry-run command
neo4j-admin restore --from=/data/.restore/data/testdb --database=testdb --force --verbose
Volume mounts and sizing
Filesystem      Size  Used Avail Use% Mounted on
none             97G   36G   62G  37% /
tmpfs           119G     0  119G   0% /dev
tmpfs           119G     0  119G   0% /sys/fs/cgroup
/dev/sda1        97G   36G   62G  37% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs           119G     0  119G   0% /proc/acpi
tmpfs           119G     0  119G   0% /sys/firmware
tmpfs           119G     0  119G   0% /proc/scsi
Now restoring
neo4j 4.1.0
VM Name: OpenJDK 64-Bit Server VM
VM Vendor: Debian
VM Version: 11.0.6+10-post-Debian-1bpo91
JIT compiler: HotSpot 64-Bit Tiered Compilers
VM Arguments: [-XX:+UseParallelGC, -Dfile.encoding=UTF-8]
java.lang.IllegalArgumentException: Source directory does not exist [/data/.restore/data/testdb]
	at com.neo4j.restore.RestoreDatabaseCommand.execute(RestoreDatabaseCommand.java:49)
	at com.neo4j.restore.RestoreDatabaseCli.execute(RestoreDatabaseCli.java:59)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:67)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:77)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:58)
Restore process failed; will not continue
Failed to restore testdb
All finished

```

**Comment by moxious** [comment]
Your logs are omitting key lines that would help figure this out, can you post a complete log?

1. First the /data/.restore dir gets created
2. Then you copy from cloud storage
3. Then you unzip to /data/.restore
4. Then you run the neo4j-restore tool FROM /data/.restore/data/testdb
5. This doesn't exist so you fail.

It looks to me like steps 1, 2, 3 all work correctly.    But the issue is that your backup set doesn't have the right directory structure.  Restore tries to restore from /data/.restore/data/testdb but it seems like the unzip is happening to /data/.restore/testdb, which doesn't match.

Was the backup created with the corresponding backup helm chart?

The other stuff you're noticing is leftover code that needs cleanup.   An earleir version of backup & restore was more fancy and allowed for uncompressed backup sets, but this is no longer a target of the tool.

**Comment by moxious** [comment]
@bugzyz any further information here?

**Comment by bugzyz** [comment]
Got it. I don't have any further information. Thanks for your answer! 👍
